import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1686573644350 implements MigrationInterface {
    name = 'Migration1686573644350'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`item_category\` (\`item_category_id\` int NOT NULL AUTO_INCREMENT COMMENT 'PK of the table.', \`code\` varchar(50) NOT NULL COMMENT 'Unique code of the item category.', \`item_category_name\` varchar(100) NOT NULL COMMENT 'Name of the item category.', \`remarks\` varchar(8000) NULL COMMENT 'Name of the item category.', \`createdby\` int NOT NULL COMMENT 'User id of a user who created the record.', \`createddate\` datetime NOT NULL COMMENT 'Date and time when the record is created.', \`modifiedby\` int NULL COMMENT 'User id of a user who modified the record.', \`modifieddate\` datetime NULL COMMENT 'Date and time when the record is modified.', \`issystem\` tinyint NOT NULL COMMENT 'Is generated by the system.', UNIQUE INDEX \`IDX_7173efc7a9b80590cd4f5a0026\` (\`item_category_id\`), UNIQUE INDEX \`IDX_d07bbc72c8822787efab782a6c\` (\`code\`), PRIMARY KEY (\`item_category_id\`)) ENGINE=InnoDB`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`IDX_d07bbc72c8822787efab782a6c\` ON \`item_category\``);
        await queryRunner.query(`DROP INDEX \`IDX_7173efc7a9b80590cd4f5a0026\` ON \`item_category\``);
        await queryRunner.query(`DROP TABLE \`item_category\``);
    }

}
